export interface ManualOffer {
  homeKey: string;
  awayKey: string;
  date: string;
  providerName: string;
  priceSEK: number;
  ticketType: string;
  productType: 'biljett' | 'hotell' | 'flyg';
  bookingUrl: string;
}

export const MANUAL_OFFERS: ManualOffer[] = [
  // --- MATCH 1: Real Madrid vs Villarreal (3 paket) ---
  {
    homeKey: "real-madrid",
    awayKey: "villarreal",
    date: "2026-10-10",
    providerName: "Olka Express",
    priceSEK: 3105,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-10-real-madrid-villarreal?eventPackage=ticket",
  },
  {
    homeKey: "real-madrid",
    awayKey: "villarreal",
    date: "2026-10-10",
    providerName: "Olka Express",
    priceSEK: 7760,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-10-real-madrid-villarreal?eventPackage=hotel",
  },
  {
    homeKey: "real-madrid",
    awayKey: "villarreal",
    date: "2026-10-10",
    providerName: "Olka Express",
    priceSEK: 12335,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-10-real-madrid-villarreal?eventPackage=flight",
  }, // <--- VIKTIGT: Ett kommatecken mellan blocken!

  // --- MATCH 2: Exempel på en till match (t.ex. Barcelona) ---
  {
    homeKey: "liverpool",
    awayKey: "manchester-city",
    date: "2026-10-11",
    providerName: "Olka Express",
    priceSEK: 7125,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-11-liverpool-fc-manchester-city?eventPackage=ticket",
  },
  {
    homeKey: "liverpool",
    awayKey: "manchester-city",
    date: "2026-10-11",
    providerName: "Olka Express",
    priceSEK: 9920,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-11-liverpool-fc-manchester-city?eventPackage=hotel",
  },
  {
    homeKey: "manchester-city",
    awayKey: "psg",
    date: "2026-10-14",
    providerName: "Olka Express",
    priceSEK: 2945,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-14-manchester-city-paris-saint-germain?eventPackage=ticket",
  },
  {
    homeKey: "manchester-city",
    awayKey: "psg",
    date: "2026-10-14",
    providerName: "Olka Express",
    priceSEK: 4170,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-14-manchester-city-paris-saint-germain?eventPackage=hotel",
  },
  {
    homeKey: "manchester-city",
    awayKey: "psg",
    date: "2026-10-14",
    providerName: "Olka Express",
    priceSEK: 8155,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-14-manchester-city-paris-saint-germain?eventPackage=flight",
  },
  {
    homeKey: "psg",
    awayKey: "barcelona",
    date: "2026-10-20",
    providerName: "Olka Express",
    priceSEK: 12415,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-20-paris-saint-germain-fc-barcelona?eventPackage=ticket",
  },
  {
    homeKey: "psg",
    awayKey: "barcelona",
    date: "2026-10-20",
    providerName: "Olka Express",
    priceSEK: 15960,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-20-paris-saint-germain-fc-barcelona?eventPackage=hotel",
  },
  {
    homeKey: "psg",
    awayKey: "barcelona",
    date: "2026-10-20",
    providerName: "Olka Express",
    priceSEK: 19115,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-20-paris-saint-germain-fc-barcelona?eventPackage=flight",
  },
  {
    homeKey: "bayern-munchen",
    awayKey: "arsenal",
    date: "2026-10-21",
    providerName: "Olka Express",
    priceSEK: 6925,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-21-bayern-mnchen-arsenal?eventPackage=ticket",
  },
  {
    homeKey: "bayern-munchen",
    awayKey: "arsenal",
    date: "2026-10-21",
    providerName: "Olka Express",
    priceSEK: 8880,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-21-bayern-mnchen-arsenal?eventPackage=hotel",
  },
  {
    homeKey: "bayern-munchen",
    awayKey: "arsenal",
    date: "2026-10-21",
    providerName: "Olka Express",
    priceSEK: 12335,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-21-bayern-mnchen-arsenal?eventPackage=flight",
  },
  {
    homeKey: "chelsea",
    awayKey: "tottenham",
    date: "2026-10-24",
    providerName: "Olka Express",
    priceSEK: 4995,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-24-chelsea-fc-tottenham-hotspur?eventPackage=ticket",
  },
  {
    homeKey: "chelsea",
    awayKey: "tottenham",
    date: "2026-10-24",
    providerName: "Olka Express",
    priceSEK: 6190,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-24-chelsea-fc-tottenham-hotspur?eventPackage=hotel",
  },
  {
    homeKey: "chelsea",
    awayKey: "tottenham",
    date: "2026-10-24",
    providerName: "Olka Express",
    priceSEK: 10125,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-24-chelsea-fc-tottenham-hotspur?eventPackage=flight",
  },
  {
    homeKey: "barcelona",
    awayKey: "real-madrid",
    date: "2026-10-25",
    providerName: "Olka Express",
    priceSEK: 19275,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-25-fc-barcelona-real-madrid?eventPackage=ticket",
  },
  {
    homeKey: "barcelona",
    awayKey: "real-madrid",
    date: "2026-10-25",
    providerName: "Olka Express",
    priceSEK: 21730,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-25-fc-barcelona-real-madrid?eventPackage=hotel",
  },
  {
    homeKey: "barcelona",
    awayKey: "real-madrid",
    date: "2026-10-25",
    providerName: "Olka Express",
    priceSEK: 25925,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-25-fc-barcelona-real-madrid?eventPackage=flight",
  },
  {
    homeKey: "bayern-munchen",
    awayKey: "borussia-dortmund",
    date: "2026-10-31",
    providerName: "Olka Express",
    priceSEK: 9745,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-31-bayern-mnchen-borussia-dortmund?eventPackage=ticket",
  },
  {
    homeKey: "bayern-munchen",
    awayKey: "borussia-dortmund",
    date: "2026-10-31",
    providerName: "Olka Express",
    priceSEK: 11080,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-31-bayern-mnchen-borussia-dortmund?eventPackage=hotel",
  },
  {
    homeKey: "bayern-munchen",
    awayKey: "borussia-dortmund",
    date: "2026-10-31",
    providerName: "Olka Express",
    priceSEK: 14535,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-31-bayern-mnchen-borussia-dortmund?eventPackage=flight",
  },
  {
    homeKey: "milan",
    awayKey: "inter",
    date: "2026-10-31",
    providerName: "Olka Express",
    priceSEK: 2975,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-31-ac-milan-inter?eventPackage=ticket",
  },
  {
    homeKey: "milan",
    awayKey: "inter",
    date: "2026-10-31",
    providerName: "Olka Express",
    priceSEK: 4080,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-31-ac-milan-inter?eventPackage=hotel",
  },
  {
    homeKey: "milan",
    awayKey: "inter",
    date: "2026-10-31",
    providerName: "Olka Express",
    priceSEK: 6765,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-31-ac-milan-inter?eventPackage=flight",
  },
  {
    homeKey: "liverpool",
    awayKey: "arsenal",
    date: "2026-11-01",
    providerName: "Olka Express",
    priceSEK: 8385,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-01-liverpool-fc-arsenal?eventPackage=ticket",
  },
  {
    homeKey: "liverpool",
    awayKey: "arsenal",
    date: "2026-11-01",
    providerName: "Olka Express",
    priceSEK: 9960,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-01-liverpool-fc-arsenal?eventPackage=hotel",
  },
  {
    homeKey: "liverpool",
    awayKey: "arsenal",
    date: "2026-11-01",
    providerName: "Olka Express",
    priceSEK: 14635,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-01-liverpool-fc-arsenal?eventPackage=flight",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "manchester-united",
    date: "2026-10-13",
    providerName: "Olka Express",
    priceSEK: 2315,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-13-atltico-madrid-manchester-united?eventPackage=ticket",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "manchester-united",
    date: "2026-10-13",
    providerName: "Olka Express",
    priceSEK: 4400,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-13-atltico-madrid-manchester-united?eventPackage=hotel",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "manchester-united",
    date: "2026-10-13",
    providerName: "Olka Express",
    priceSEK: 9205,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-10-13-atltico-madrid-manchester-united?eventPackage=flight",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "bayern-munchen",
    date: "2026-11-03",
    providerName: "Olka Express",
    priceSEK: 2955,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-03-atltico-madrid-bayern-mnchen?eventPackage=ticket",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "bayern-munchen",
    date: "2026-11-03",
    providerName: "Olka Express",
    priceSEK: 5340,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-03-atltico-madrid-bayern-mnchen?eventPackage=hotel",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "bayern-munchen",
    date: "2026-11-03",
    providerName: "Olka Express",
    priceSEK: 8875,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-03-atltico-madrid-bayern-mnchen?eventPackage=flight",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "barcelona",
    date: "2026-11-08",
    providerName: "Olka Express",
    priceSEK: 3995,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-08-atltico-madrid-fc-barcelona?eventPackage=ticket",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "barcelona",
    date: "2026-11-08",
    providerName: "Olka Express",
    priceSEK: 5840,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-08-atltico-madrid-fc-barcelona?eventPackage=hotel",
  },
  {
    homeKey: "atletico-madrid",
    awayKey: "barcelona",
    date: "2026-11-08",
    providerName: "Olka Express",
    priceSEK: 10485,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-08-atltico-madrid-fc-barcelona?eventPackage=flight",
  },
  {
    homeKey: "arsenal",
    awayKey: "borussia-dortmund",
    date: "2026-11-24",
    providerName: "Olka Express",
    priceSEK: 7585,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-24-arsenal--borussia-dortmund?eventPackage=ticket",
  },
  {
    homeKey: "arsenal",
    awayKey: "borussia-dortmund",
    date: "2026-11-24",
    providerName: "Olka Express",
    priceSEK: 8550,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-24-arsenal--borussia-dortmund?eventPackage=hotel",
  },
  {
    homeKey: "arsenal",
    awayKey: "borussia-dortmund",
    date: "2026-11-24",
    providerName: "Olka Express",
    priceSEK: 10585,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-24-arsenal--borussia-dortmund?eventPackage=flight",
  },
  {
    homeKey: "arsenal",
    awayKey: "manchester-city",
    date: "2026-11-29",
    providerName: "Olka Express",
    priceSEK: 14765,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-29-arsenal--manchester-city?eventPackage=ticket",
  },
  {
    homeKey: "arsenal",
    awayKey: "manchester-city",
    date: "2026-11-29",
    providerName: "Olka Express",
    priceSEK: 15760,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-29-arsenal--manchester-city?eventPackage=hotel",
  },
  {
    homeKey: "arsenal",
    awayKey: "manchester-city",
    date: "2026-11-29",
    providerName: "Olka Express",
    priceSEK: 18295,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-11-29-arsenal--manchester-city?eventPackage=flight",
  },
  {
    homeKey: "chelsea",
    awayKey: "liverpool",
    date: "2026-12-05",
    providerName: "Olka Express",
    priceSEK: 6995,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-12-05-chelsea-fc-liverpool-fc?eventPackage=ticket",
  },
  {
    homeKey: "chelsea",
    awayKey: "liverpool",
    date: "2026-12-05",
    providerName: "Olka Express",
    priceSEK: 8190,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-12-05-chelsea-fc-liverpool-fc?eventPackage=hotel",
  },
  {
    homeKey: "chelsea",
    awayKey: "liverpool",
    date: "2026-12-05",
    providerName: "Olka Express",
    priceSEK: 11495,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-12-05-chelsea-fc-liverpool-fc?eventPackage=flight",
  },
  {
    homeKey: "tottenham",
    awayKey: "arsenal",
    date: "2026-12-05",
    providerName: "Olka Express",
    priceSEK: 3795,
    ticketType: "Endast biljett",
    productType: "biljett",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-12-05-tottenham-hotspur-arsenal?eventPackage=ticket",
  },
  {
    homeKey: "tottenham",
    awayKey: "arsenal",
    date: "2026-12-05",
    providerName: "Olka Express",
    priceSEK: 4990,
    ticketType: "Paket med hotell",
    productType: "hotell",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-12-05-tottenham-hotspur-arsenal?eventPackage=hotel",
  },
  {
    homeKey: "tottenham",
    awayKey: "arsenal",
    date: "2026-12-05",
    providerName: "Olka Express",
    priceSEK: 8295,
    ticketType: "Paket med hotell & flyg",
    productType: "flyg",
    bookingUrl: "https://clk.tradedoubler.com/click?p=355835&a=3495104&url=https://www.olkaexpress.se/events/soccer/2026-12-05-tottenham-hotspur-arsenal?eventPackage=flight",
  },

];


// Funktionen som söker fram priserna för en specifik match
export function getManualOffersForMatch(homeKey: string, awayKey: string, date: string) {
  return MANUAL_OFFERS.filter(
    (offer) => 
      offer.homeKey === homeKey && 
      offer.awayKey === awayKey && 
      offer.date === date
  );
}